# .github/workflows/fetch.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'elysias123'
          git config --global user.email '118418714+elysias123@users.noreply.github.com'
          git config --global credential.helper store
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/Innei/Shiro.git tmp
          cd tmp
          git remote add upstream https://${{ secrets.PAT_TOKEN }}@github.com/organization/website.git
          git fetch upstream
          git merge upstream/master
          git push origin master          
